# Generated by Django 6.0.3 on 2026-04-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_name', models.CharField(max_length=100)),
                ('sequence', models.TextField()),
                ('fasta_file', models.FileField(upload_to='outputs/fasta/')),
                ('rcsb_csv', models.FileField(upload_to='outputs/rcsb/')),
                ('merged_csv', models.FileField(upload_to='outputs/merged/')),
                ('plot_files', models.JSONField(blank=True, default=list)),
                ('pdf_files', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
