# Generated by Django 6.1 on 2026-08-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_name', models.CharField(max_length=200)),
                ('folder_name', models.CharField(help_text='Output directory name under PIPELINE_OUTPUT_DIR; also the results/download URL key.', max_length=220, unique=True)),
                ('sequence_type', models.CharField(max_length=10)),
                ('identity', models.FloatField()),
                ('evalue', models.FloatField()),
                ('max_hits', models.IntegerField()),
                ('llm_fallback', models.BooleanField(default=False)),
                ('sequence_preview', models.CharField(blank=True, help_text='First few residues, just enough to recognize the run at a glance.', max_length=80)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
