# Generated by Django 6.1 on 2026-08-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrun',
            name='runtime_seconds',
            field=models.FloatField(default=0.0, help_text='Time spent running the pipeline.'),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='search_signature',
            field=models.CharField(blank=True, db_index=True, help_text='Canonical signature for deduplicating repeated searches.', max_length=128),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='sequence',
            field=models.TextField(blank=True, help_text='Original sequence used for the search.'),
        ),
    ]
