# Generated by Django 6.0.5 on 2026-09-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_searchrun_runtime_seconds_searchrun_search_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrun',
            name='sequence_signature',
            field=models.CharField(blank=True, db_index=True, help_text='Signature of protein name + sequence + sequence type only (no thresholds/flags) -- a rerun with the same subject but different parameters reuses and overwrites this row instead of creating a new history entry.', max_length=128),
        ),
    ]
